# coding: utf-8

# flake8: noqa
"""
    F-UJI

    A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).  # noqa: E501

    OpenAPI spec version: 3.0.1
    Contact: anusuriya.devaraju@googlemail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.any_of_fair_results_results_items import AnyOfFAIRResultsResultsItems
from swagger_client.models.body import Body
from swagger_client.models.community_endorsed_standard import CommunityEndorsedStandard
from swagger_client.models.community_endorsed_standard_output import CommunityEndorsedStandardOutput
from swagger_client.models.community_endorsed_standard_output_inner import CommunityEndorsedStandardOutputInner
from swagger_client.models.core_metadata import CoreMetadata
from swagger_client.models.core_metadata_output import CoreMetadataOutput
from swagger_client.models.data_access_level import DataAccessLevel
from swagger_client.models.data_access_output import DataAccessOutput
from swagger_client.models.data_content_metadata import DataContentMetadata
from swagger_client.models.data_content_metadata_output import DataContentMetadataOutput
from swagger_client.models.data_content_metadata_output_inner import DataContentMetadataOutputInner
from swagger_client.models.data_file_format import DataFileFormat
from swagger_client.models.data_file_format_output import DataFileFormatOutput
from swagger_client.models.data_file_format_output_inner import DataFileFormatOutputInner
from swagger_client.models.data_provenance import DataProvenance
from swagger_client.models.data_provenance_output import DataProvenanceOutput
from swagger_client.models.data_provenance_output_inner import DataProvenanceOutputInner
from swagger_client.models.debug import Debug
from swagger_client.models.fair_result_common import FAIRResultCommon
from swagger_client.models.fair_result_common_score import FAIRResultCommonScore
from swagger_client.models.fair_result_evaluation_criterium import FAIRResultEvaluationCriterium
from swagger_client.models.fair_results import FAIRResults
from swagger_client.models.formal_metadata import FormalMetadata
from swagger_client.models.formal_metadata_output import FormalMetadataOutput
from swagger_client.models.formal_metadata_output_inner import FormalMetadataOutputInner
from swagger_client.models.harvest import Harvest
from swagger_client.models.harvest_results import HarvestResults
from swagger_client.models.harvest_results_metadata import HarvestResultsMetadata
from swagger_client.models.identifier_included import IdentifierIncluded
from swagger_client.models.identifier_included_output import IdentifierIncludedOutput
from swagger_client.models.identifier_included_output_inner import IdentifierIncludedOutputInner
from swagger_client.models.license import License
from swagger_client.models.license_output import LicenseOutput
from swagger_client.models.license_output_inner import LicenseOutputInner
from swagger_client.models.metadata_preserved import MetadataPreserved
from swagger_client.models.metadata_preserved_output import MetadataPreservedOutput
from swagger_client.models.metric import Metric
from swagger_client.models.metrics import Metrics
from swagger_client.models.output_core_metadata_found import OutputCoreMetadataFound
from swagger_client.models.output_search_mechanisms import OutputSearchMechanisms
from swagger_client.models.persistence import Persistence
from swagger_client.models.persistence_output import PersistenceOutput
from swagger_client.models.persistence_output_inner import PersistenceOutputInner
from swagger_client.models.related_resource import RelatedResource
from swagger_client.models.related_resource_output import RelatedResourceOutput
from swagger_client.models.related_resource_output_inner import RelatedResourceOutputInner
from swagger_client.models.searchable import Searchable
from swagger_client.models.searchable_output import SearchableOutput
from swagger_client.models.semantic_vocabulary import SemanticVocabulary
from swagger_client.models.semantic_vocabulary_output import SemanticVocabularyOutput
from swagger_client.models.semantic_vocabulary_output_inner import SemanticVocabularyOutputInner
from swagger_client.models.standardised_protocol_data import StandardisedProtocolData
from swagger_client.models.standardised_protocol_data_output import StandardisedProtocolDataOutput
from swagger_client.models.standardised_protocol_metadata import StandardisedProtocolMetadata
from swagger_client.models.standardised_protocol_metadata_output import StandardisedProtocolMetadataOutput
from swagger_client.models.uniqueness import Uniqueness
from swagger_client.models.uniqueness_output import UniquenessOutput
