from fuji_server import util
from fuji_server.models.base_model_ import Model


class CommunityEndorsedStandardOutputInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self,
        metadata_standard: str = None,
        url: str = None,
        subject_areas: list[str] = None,
        type: str = None,
        source: str = None,
    ):  # noqa: E501
        """CommunityEndorsedStandardOutputInner - a model defined in Swagger

        :param metadata_standard: The metadata_standard of this CommunityEndorsedStandardOutputInner.  # noqa: E501
        :type metadata_standard: str
        :param url: The url of this CommunityEndorsedStandardOutputInner.  # noqa: E501
        :type url: str
        :param subject_areas: The subject_areas of this CommunityEndorsedStandardOutputInner.  # noqa: E501
        :type subject_areas: List[str]
        :param type: The type of this CommunityEndorsedStandardOutputInner.  # noqa: E501
        :type type: str
        :param source: The source of this CommunityEndorsedStandardOutputInner.  # noqa: E501
        :type source: str
        """
        self.swagger_types = {
            "metadata_standard": str,
            "url": str,
            "subject_areas": list[str],
            "type": str,
            "source": str,
        }

        self.attribute_map = {
            "metadata_standard": "metadata_standard",
            "url": "url",
            "subject_areas": "subject_areas",
            "type": "type",
            "source": "source",
        }
        self._metadata_standard = metadata_standard
        self._url = url
        self._subject_areas = subject_areas
        self._type = type
        self._source = source

    @classmethod
    def from_dict(cls, dikt) -> "CommunityEndorsedStandardOutputInner":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CommunityEndorsedStandard_output_inner of this CommunityEndorsedStandardOutputInner.  # noqa: E501
        :rtype: CommunityEndorsedStandardOutputInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata_standard(self) -> str:
        """Gets the metadata_standard of this CommunityEndorsedStandardOutputInner.


        :return: The metadata_standard of this CommunityEndorsedStandardOutputInner.
        :rtype: str
        """
        return self._metadata_standard

    @metadata_standard.setter
    def metadata_standard(self, metadata_standard: str):
        """Sets the metadata_standard of this CommunityEndorsedStandardOutputInner.


        :param metadata_standard: The metadata_standard of this CommunityEndorsedStandardOutputInner.
        :type metadata_standard: str
        """

        self._metadata_standard = metadata_standard

    @property
    def url(self) -> str:
        """Gets the url of this CommunityEndorsedStandardOutputInner.


        :return: The url of this CommunityEndorsedStandardOutputInner.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this CommunityEndorsedStandardOutputInner.


        :param url: The url of this CommunityEndorsedStandardOutputInner.
        :type url: str
        """

        self._url = url

    @property
    def subject_areas(self) -> list[str]:
        """Gets the subject_areas of this CommunityEndorsedStandardOutputInner.


        :return: The subject_areas of this CommunityEndorsedStandardOutputInner.
        :rtype: List[str]
        """
        return self._subject_areas

    @subject_areas.setter
    def subject_areas(self, subject_areas: list[str]):
        """Sets the subject_areas of this CommunityEndorsedStandardOutputInner.


        :param subject_areas: The subject_areas of this CommunityEndorsedStandardOutputInner.
        :type subject_areas: List[str]
        """

        self._subject_areas = subject_areas

    @property
    def type(self) -> str:
        """Gets the type of this CommunityEndorsedStandardOutputInner.


        :return: The type of this CommunityEndorsedStandardOutputInner.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this CommunityEndorsedStandardOutputInner.


        :param type: The type of this CommunityEndorsedStandardOutputInner.
        :type type: str
        """

        self._type = type

    @property
    def source(self) -> str:
        """Gets the source of this CommunityEndorsedStandardOutputInner.


        :return: The source of this CommunityEndorsedStandardOutputInner.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source: str):
        """Sets the source of this CommunityEndorsedStandardOutputInner.


        :param source: The source of this CommunityEndorsedStandardOutputInner.
        :type source: str
        """

        self._source = source
