# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fuji_server.models.base_model_ import Model
from fuji_server import util


class CommunityEndorsedStandardOutputInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, metadata_standard: str=None, subject_areas: List[str]=None):  # noqa: E501
        """CommunityEndorsedStandardOutputInner - a model defined in Swagger

        :param metadata_standard: The metadata_standard of this CommunityEndorsedStandardOutputInner.  # noqa: E501
        :type metadata_standard: str
        :param subject_areas: The subject_areas of this CommunityEndorsedStandardOutputInner.  # noqa: E501
        :type subject_areas: List[str]
        """
        self.swagger_types = {
            'metadata_standard': str,
            'subject_areas': List[str]
        }

        self.attribute_map = {
            'metadata_standard': 'metadata_standard',
            'subject_areas': 'subject_areas'
        }
        self._metadata_standard = metadata_standard
        self._subject_areas = subject_areas

    @classmethod
    def from_dict(cls, dikt) -> 'CommunityEndorsedStandardOutputInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CommunityEndorsedStandard_output_inner of this CommunityEndorsedStandardOutputInner.  # noqa: E501
        :rtype: CommunityEndorsedStandardOutputInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata_standard(self) -> str:
        """Gets the metadata_standard of this CommunityEndorsedStandardOutputInner.


        :return: The metadata_standard of this CommunityEndorsedStandardOutputInner.
        :rtype: str
        """
        return self._metadata_standard

    @metadata_standard.setter
    def metadata_standard(self, metadata_standard: str):
        """Sets the metadata_standard of this CommunityEndorsedStandardOutputInner.


        :param metadata_standard: The metadata_standard of this CommunityEndorsedStandardOutputInner.
        :type metadata_standard: str
        """

        self._metadata_standard = metadata_standard

    @property
    def subject_areas(self) -> List[str]:
        """Gets the subject_areas of this CommunityEndorsedStandardOutputInner.


        :return: The subject_areas of this CommunityEndorsedStandardOutputInner.
        :rtype: List[str]
        """
        return self._subject_areas

    @subject_areas.setter
    def subject_areas(self, subject_areas: List[str]):
        """Sets the subject_areas of this CommunityEndorsedStandardOutputInner.


        :param subject_areas: The subject_areas of this CommunityEndorsedStandardOutputInner.
        :type subject_areas: List[str]
        """

        self._subject_areas = subject_areas
