from fuji_server import util
from fuji_server.models.base_model_ import Model


class CommunityEndorsedStandardOutput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self):
        """CommunityEndorsedStandardOutput - a model defined in Swagger"""
        self.swagger_types = {}

        self.attribute_map = {}

    @classmethod
    def from_dict(cls, dikt) -> "CommunityEndorsedStandardOutput":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CommunityEndorsedStandard_output of this CommunityEndorsedStandardOutput.  # noqa: E501
        :rtype: CommunityEndorsedStandardOutput
        """
        return util.deserialize_model(dikt, cls)
