from fuji_server import util
from fuji_server.models.base_model_ import Model


class DataContentMetadataOutputInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self, descriptor: str | None = None, descriptor_value: str | None = None, matches_content: bool = False
    ):
        """DataContentMetadataOutputInner - a model defined in Swagger

        :param descriptor: The descriptor of this DataContentMetadataOutputInner.  # noqa: E501
        :type descriptor: str
        :param descriptor_value: The descriptor_value of this DataContentMetadataOutputInner.  # noqa: E501
        :type descriptor_value: str
        :param matches_content: The matches_content of this DataContentMetadataOutputInner.  # noqa: E501
        :type matches_content: bool
        """
        self.swagger_types = {"descriptor": str, "descriptor_value": str, "matches_content": bool}

        self.attribute_map = {
            "descriptor": "descriptor",
            "descriptor_value": "descriptor_value",
            "matches_content": "matches_content",
        }
        self._descriptor = descriptor
        self._descriptor_value = descriptor_value
        self._matches_content = matches_content

    @classmethod
    def from_dict(cls, dikt) -> "DataContentMetadataOutputInner":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataContentMetadata_output_inner of this DataContentMetadataOutputInner.  # noqa: E501
        :rtype: DataContentMetadataOutputInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def descriptor(self) -> str:
        """Gets the descriptor of this DataContentMetadataOutputInner.


        :return: The descriptor of this DataContentMetadataOutputInner.
        :rtype: str
        """
        return self._descriptor

    @descriptor.setter
    def descriptor(self, descriptor: str):
        """Sets the descriptor of this DataContentMetadataOutputInner.


        :param descriptor: The descriptor of this DataContentMetadataOutputInner.
        :type descriptor: str
        """

        self._descriptor = descriptor

    @property
    def descriptor_value(self) -> str:
        """Gets the descriptor_value of this DataContentMetadataOutputInner.


        :return: The descriptor_value of this DataContentMetadataOutputInner.
        :rtype: str
        """
        return self._descriptor_value

    @descriptor_value.setter
    def descriptor_value(self, descriptor_value: str):
        """Sets the descriptor_value of this DataContentMetadataOutputInner.


        :param descriptor_value: The descriptor_value of this DataContentMetadataOutputInner.
        :type descriptor_value: str
        """

        self._descriptor_value = descriptor_value

    @property
    def matches_content(self) -> bool:
        """Gets the matches_content of this DataContentMetadataOutputInner.


        :return: The matches_content of this DataContentMetadataOutputInner.
        :rtype: bool
        """
        return self._matches_content

    @matches_content.setter
    def matches_content(self, matches_content: bool):
        """Sets the matches_content of this DataContentMetadataOutputInner.


        :param matches_content: The matches_content of this DataContentMetadataOutputInner.
        :type matches_content: bool
        """

        self._matches_content = matches_content
