# -*- coding: utf-8 -*-

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from fuji_server import util
from fuji_server.models.base_model_ import Model
from fuji_server.models.data_file_format_output_inner import DataFileFormatOutputInner  # noqa: F401,E501


class DataFileFormatOutput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """DataFileFormatOutput - a model defined in Swagger"""
        self.swagger_types = {}

        self.attribute_map = {}

    @classmethod
    def from_dict(cls, dikt) -> "DataFileFormatOutput":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataFileFormat_output of this DataFileFormatOutput.  # noqa: E501
        :rtype: DataFileFormatOutput
        """
        return util.deserialize_model(dikt, cls)
