# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fuji_server.models.base_model_ import Model
from fuji_server import util


class DataContentMetadataOutputInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, descriptor_name: str=None, descriptor_type: str=None, matchescontent: bool=False):  # noqa: E501
        """DataContentMetadataOutputInner - a model defined in Swagger

        :param descriptor_name: The descriptor_name of this DataContentMetadataOutputInner.  # noqa: E501
        :type descriptor_name: str
        :param descriptor_type: The descriptor_type of this DataContentMetadataOutputInner.  # noqa: E501
        :type descriptor_type: str
        :param matchescontent: The matchescontent of this DataContentMetadataOutputInner.  # noqa: E501
        :type matchescontent: bool
        """
        self.swagger_types = {
            'descriptor_name': str,
            'descriptor_type': str,
            'matchescontent': bool
        }

        self.attribute_map = {
            'descriptor_name': 'descriptor_name',
            'descriptor_type': 'descriptor_type',
            'matchescontent': 'matchescontent'
        }
        self._descriptor_name = descriptor_name
        self._descriptor_type = descriptor_type
        self._matchescontent = matchescontent

    @classmethod
    def from_dict(cls, dikt) -> 'DataContentMetadataOutputInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataContentMetadata_output_inner of this DataContentMetadataOutputInner.  # noqa: E501
        :rtype: DataContentMetadataOutputInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def descriptor_name(self) -> str:
        """Gets the descriptor_name of this DataContentMetadataOutputInner.


        :return: The descriptor_name of this DataContentMetadataOutputInner.
        :rtype: str
        """
        return self._descriptor_name

    @descriptor_name.setter
    def descriptor_name(self, descriptor_name: str):
        """Sets the descriptor_name of this DataContentMetadataOutputInner.


        :param descriptor_name: The descriptor_name of this DataContentMetadataOutputInner.
        :type descriptor_name: str
        """

        self._descriptor_name = descriptor_name

    @property
    def descriptor_type(self) -> str:
        """Gets the descriptor_type of this DataContentMetadataOutputInner.


        :return: The descriptor_type of this DataContentMetadataOutputInner.
        :rtype: str
        """
        return self._descriptor_type

    @descriptor_type.setter
    def descriptor_type(self, descriptor_type: str):
        """Sets the descriptor_type of this DataContentMetadataOutputInner.


        :param descriptor_type: The descriptor_type of this DataContentMetadataOutputInner.
        :type descriptor_type: str
        """

        self._descriptor_type = descriptor_type

    @property
    def matchescontent(self) -> bool:
        """Gets the matchescontent of this DataContentMetadataOutputInner.


        :return: The matchescontent of this DataContentMetadataOutputInner.
        :rtype: bool
        """
        return self._matchescontent

    @matchescontent.setter
    def matchescontent(self, matchescontent: bool):
        """Sets the matchescontent of this DataContentMetadataOutputInner.


        :param matchescontent: The matchescontent of this DataContentMetadataOutputInner.
        :type matchescontent: bool
        """

        self._matchescontent = matchescontent
