"""
    F-UJI

    A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).  # noqa: E501

    OpenAPI spec version: 3.0.1
    Contact: anusuriya.devaraju@googlemail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class FormalMetadataOutputInner:
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"serialization_format": "str", "source": "str", "is_metadata_found": "bool"}

    attribute_map = {
        "serialization_format": "serialization_format",
        "source": "source",
        "is_metadata_found": "is_metadata_found",
    }

    def __init__(self, serialization_format=None, source=None, is_metadata_found=False):
        """FormalMetadataOutputInner - a model defined in Swagger"""
        self._serialization_format = None
        self._source = None
        self._is_metadata_found = None
        self.discriminator = None
        if serialization_format is not None:
            self.serialization_format = serialization_format
        if source is not None:
            self.source = source
        if is_metadata_found is not None:
            self.is_metadata_found = is_metadata_found

    @property
    def serialization_format(self):
        """Gets the serialization_format of this FormalMetadataOutputInner.  # noqa: E501


        :return: The serialization_format of this FormalMetadataOutputInner.  # noqa: E501
        :rtype: str
        """
        return self._serialization_format

    @serialization_format.setter
    def serialization_format(self, serialization_format):
        """Sets the serialization_format of this FormalMetadataOutputInner.


        :param serialization_format: The serialization_format of this FormalMetadataOutputInner.  # noqa: E501
        :type: str
        """

        self._serialization_format = serialization_format

    @property
    def source(self):
        """Gets the source of this FormalMetadataOutputInner.  # noqa: E501


        :return: The source of this FormalMetadataOutputInner.  # noqa: E501
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this FormalMetadataOutputInner.


        :param source: The source of this FormalMetadataOutputInner.  # noqa: E501
        :type: str
        """
        allowed_values = ["typed_link", "content_negotiate", "structured_data", "sparql_endpoint"]
        if source not in allowed_values:
            raise ValueError(f"Invalid value for `source` ({source}), must be one of {allowed_values}")

        self._source = source

    @property
    def is_metadata_found(self):
        """Gets the is_metadata_found of this FormalMetadataOutputInner.  # noqa: E501


        :return: The is_metadata_found of this FormalMetadataOutputInner.  # noqa: E501
        :rtype: bool
        """
        return self._is_metadata_found

    @is_metadata_found.setter
    def is_metadata_found(self, is_metadata_found):
        """Sets the is_metadata_found of this FormalMetadataOutputInner.


        :param is_metadata_found: The is_metadata_found of this FormalMetadataOutputInner.  # noqa: E501
        :type: bool
        """

        self._is_metadata_found = is_metadata_found

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(FormalMetadataOutputInner, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FormalMetadataOutputInner):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
