# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fuji_server.models.base_model_ import Model
from fuji_server import util


class IdentifierIncludedOutputInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data_identifier_included: str=None, data_identifier_active: bool=False):  # noqa: E501
        """IdentifierIncludedOutputInner - a model defined in Swagger

        :param data_identifier_included: The data_identifier_included of this IdentifierIncludedOutputInner.  # noqa: E501
        :type data_identifier_included: str
        :param data_identifier_active: The data_identifier_active of this IdentifierIncludedOutputInner.  # noqa: E501
        :type data_identifier_active: bool
        """
        self.swagger_types = {
            'data_identifier_included': str,
            'data_identifier_active': bool
        }

        self.attribute_map = {
            'data_identifier_included': 'data_identifier_included',
            'data_identifier_active': 'data_identifier_active'
        }
        self._data_identifier_included = data_identifier_included
        self._data_identifier_active = data_identifier_active

    @classmethod
    def from_dict(cls, dikt) -> 'IdentifierIncludedOutputInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IdentifierIncluded_output_inner of this IdentifierIncludedOutputInner.  # noqa: E501
        :rtype: IdentifierIncludedOutputInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data_identifier_included(self) -> str:
        """Gets the data_identifier_included of this IdentifierIncludedOutputInner.


        :return: The data_identifier_included of this IdentifierIncludedOutputInner.
        :rtype: str
        """
        return self._data_identifier_included

    @data_identifier_included.setter
    def data_identifier_included(self, data_identifier_included: str):
        """Sets the data_identifier_included of this IdentifierIncludedOutputInner.


        :param data_identifier_included: The data_identifier_included of this IdentifierIncludedOutputInner.
        :type data_identifier_included: str
        """

        self._data_identifier_included = data_identifier_included

    @property
    def data_identifier_active(self) -> bool:
        """Gets the data_identifier_active of this IdentifierIncludedOutputInner.


        :return: The data_identifier_active of this IdentifierIncludedOutputInner.
        :rtype: bool
        """
        return self._data_identifier_active

    @data_identifier_active.setter
    def data_identifier_active(self, data_identifier_active: bool):
        """Sets the data_identifier_active of this IdentifierIncludedOutputInner.


        :param data_identifier_active: The data_identifier_active of this IdentifierIncludedOutputInner.
        :type data_identifier_active: bool
        """

        self._data_identifier_active = data_identifier_active
