"""
    F-UJI

    A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).  # noqa: E501

    OpenAPI spec version: 3.0.1
    Contact: anusuriya.devaraju@googlemail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class LicenseOutputInner:
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"license": "str", "osi_approved": "bool", "details_url": "str"}

    attribute_map = {"license": "license", "osi_approved": "OSI_approved", "details_url": "details_url"}

    def __init__(self, license=None, osi_approved=False, details_url=None):
        """LicenseOutputInner - a model defined in Swagger"""
        self._license = None
        self._osi_approved = None
        self._details_url = None
        self.discriminator = None
        if license is not None:
            self.license = license
        if osi_approved is not None:
            self.osi_approved = osi_approved
        if details_url is not None:
            self.details_url = details_url

    @property
    def license(self):
        """Gets the license of this LicenseOutputInner.  # noqa: E501


        :return: The license of this LicenseOutputInner.  # noqa: E501
        :rtype: str
        """
        return self._license

    @license.setter
    def license(self, license):
        """Sets the license of this LicenseOutputInner.


        :param license: The license of this LicenseOutputInner.  # noqa: E501
        :type: str
        """

        self._license = license

    @property
    def osi_approved(self):
        """Gets the osi_approved of this LicenseOutputInner.  # noqa: E501


        :return: The osi_approved of this LicenseOutputInner.  # noqa: E501
        :rtype: bool
        """
        return self._osi_approved

    @osi_approved.setter
    def osi_approved(self, osi_approved):
        """Sets the osi_approved of this LicenseOutputInner.


        :param osi_approved: The osi_approved of this LicenseOutputInner.  # noqa: E501
        :type: bool
        """

        self._osi_approved = osi_approved

    @property
    def details_url(self):
        """Gets the details_url of this LicenseOutputInner.  # noqa: E501


        :return: The details_url of this LicenseOutputInner.  # noqa: E501
        :rtype: str
        """
        return self._details_url

    @details_url.setter
    def details_url(self, details_url):
        """Sets the details_url of this LicenseOutputInner.


        :param details_url: The details_url of this LicenseOutputInner.  # noqa: E501
        :type: str
        """

        self._details_url = details_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(LicenseOutputInner, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LicenseOutputInner):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
