"""
    F-UJI

    A Service for Evaluating Research Data Objects Based on <a href ='https://doi.org/10.5281/zenodo.3775793'>FAIRsFAIR Metrics</a>. <p> This work was supported by the <a href='https://www.fairsfair.eu/'>FAIRsFAIR</a> project (H2020-INFRAEOSC-2018-2020 Grant Agreement 831558).  # noqa: E501

    OpenAPI spec version: 3.0.1
    Contact: anusuriya.devaraju@googlemail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class MetadataPreservedOutput:
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"metadata_preservation_method": "list[str]"}

    attribute_map = {"metadata_preservation_method": "metadata_preservation_method"}

    def __init__(self, metadata_preservation_method=None):
        """MetadataPreservedOutput - a model defined in Swagger"""
        self._metadata_preservation_method = None
        self.discriminator = None
        if metadata_preservation_method is not None:
            self.metadata_preservation_method = metadata_preservation_method

    @property
    def metadata_preservation_method(self):
        """Gets the metadata_preservation_method of this MetadataPreservedOutput.  # noqa: E501


        :return: The metadata_preservation_method of this MetadataPreservedOutput.  # noqa: E501
        :rtype: list[str]
        """
        return self._metadata_preservation_method

    @metadata_preservation_method.setter
    def metadata_preservation_method(self, metadata_preservation_method):
        """Sets the metadata_preservation_method of this MetadataPreservedOutput.


        :param metadata_preservation_method: The metadata_preservation_method of this MetadataPreservedOutput.  # noqa: E501
        :type: list[str]
        """
        allowed_values = ["datacite", "tombstone"]
        if not set(metadata_preservation_method).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `metadata_preservation_method` [{}], must be a subset of [{}]".format(
                    ", ".join(map(str, set(metadata_preservation_method) - set(allowed_values))),
                    ", ".join(map(str, allowed_values)),
                )
            )

        self._metadata_preservation_method = metadata_preservation_method

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(MetadataPreservedOutput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MetadataPreservedOutput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
