# SPDX-FileCopyrightText: 2020 PANGAEA (https://www.pangaea.de/)
#
# SPDX-License-Identifier: MIT

from fuji_server import util
from fuji_server.models.base_model_ import Model


class OutputSearchMechanisms(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, mechanism: str | None = None, mechanism_info: list[str] | None = None):
        """OutputSearchMechanisms - a model defined in Swagger

        :param mechanism: The mechanism of this OutputSearchMechanisms.  # noqa: E501
        :type mechanism: str
        :param mechanism_info: The mechanism_info of this OutputSearchMechanisms.  # noqa: E501
        :type mechanism_info: List[str]
        """
        self.swagger_types = {"mechanism": str, "mechanism_info": list[str]}

        self.attribute_map = {"mechanism": "mechanism", "mechanism_info": "mechanism_info"}
        self._mechanism = mechanism
        self._mechanism_info = mechanism_info

    @classmethod
    def from_dict(cls, dikt) -> "OutputSearchMechanisms":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The output_search_mechanisms of this OutputSearchMechanisms.  # noqa: E501
        :rtype: OutputSearchMechanisms
        """
        return util.deserialize_model(dikt, cls)

    @property
    def mechanism(self) -> str:
        """Gets the mechanism of this OutputSearchMechanisms.


        :return: The mechanism of this OutputSearchMechanisms.
        :rtype: str
        """
        return self._mechanism

    @mechanism.setter
    def mechanism(self, mechanism: str):
        """Sets the mechanism of this OutputSearchMechanisms.


        :param mechanism: The mechanism of this OutputSearchMechanisms.
        :type mechanism: str
        """
        allowed_values = ["metadata registry", "structured data"]
        if mechanism not in allowed_values:
            raise ValueError(f"Invalid value for `mechanism` ({mechanism}), must be one of {allowed_values}")

        self._mechanism = mechanism

    @property
    def mechanism_info(self) -> list[str]:
        """Gets the mechanism_info of this OutputSearchMechanisms.


        :return: The mechanism_info of this OutputSearchMechanisms.
        :rtype: List[str]
        """
        return self._mechanism_info

    @mechanism_info.setter
    def mechanism_info(self, mechanism_info: list[str]):
        """Sets the mechanism_info of this OutputSearchMechanisms.


        :param mechanism_info: The mechanism_info of this OutputSearchMechanisms.
        :type mechanism_info: List[str]
        """

        self._mechanism_info = mechanism_info
