# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fuji_server.models.base_model_ import Model
from fuji_server import util


class OutputSearchMechanisms(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, mechanism: str=None, mechanism_info: List[str]=None):  # noqa: E501
        """OutputSearchMechanisms - a model defined in Swagger

        :param mechanism: The mechanism of this OutputSearchMechanisms.  # noqa: E501
        :type mechanism: str
        :param mechanism_info: The mechanism_info of this OutputSearchMechanisms.  # noqa: E501
        :type mechanism_info: List[str]
        """
        self.swagger_types = {
            'mechanism': str,
            'mechanism_info': List[str]
        }

        self.attribute_map = {
            'mechanism': 'mechanism',
            'mechanism_info': 'mechanism_info'
        }
        self._mechanism = mechanism
        self._mechanism_info = mechanism_info

    @classmethod
    def from_dict(cls, dikt) -> 'OutputSearchMechanisms':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The output_search_mechanisms of this OutputSearchMechanisms.  # noqa: E501
        :rtype: OutputSearchMechanisms
        """
        return util.deserialize_model(dikt, cls)

    @property
    def mechanism(self) -> str:
        """Gets the mechanism of this OutputSearchMechanisms.


        :return: The mechanism of this OutputSearchMechanisms.
        :rtype: str
        """
        return self._mechanism

    @mechanism.setter
    def mechanism(self, mechanism: str):
        """Sets the mechanism of this OutputSearchMechanisms.


        :param mechanism: The mechanism of this OutputSearchMechanisms.
        :type mechanism: str
        """
        allowed_values = ["metadata registry", "structured data"]  # noqa: E501
        if mechanism not in allowed_values:
            raise ValueError(
                "Invalid value for `mechanism` ({0}), must be one of {1}"
                .format(mechanism, allowed_values)
            )

        self._mechanism = mechanism

    @property
    def mechanism_info(self) -> List[str]:
        """Gets the mechanism_info of this OutputSearchMechanisms.


        :return: The mechanism_info of this OutputSearchMechanisms.
        :rtype: List[str]
        """
        return self._mechanism_info

    @mechanism_info.setter
    def mechanism_info(self, mechanism_info: List[str]):
        """Sets the mechanism_info of this OutputSearchMechanisms.


        :param mechanism_info: The mechanism_info of this OutputSearchMechanisms.
        :type mechanism_info: List[str]
        """

        self._mechanism_info = mechanism_info
