# SPDX-FileCopyrightText: 2020 PANGAEA (https://www.pangaea.de/)
#
# SPDX-License-Identifier: MIT

# coding: utf-8

from datetime import date, datetime  # noqa: F401

from fuji_server import util
from fuji_server.models.base_model_ import Model


class RetrievableOutputInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self,
        format: str | None = None,
        method: str | None = None,
        resolved_url: str | None = None,
        target: str | None = None,
    ):
        """RetrievableOutputInner - a model defined in Swagger

        :param format: The format of this RetrievableOutputInner.  # noqa: E501
        :type format: str
        :param method: The method of this RetrievableOutputInner.  # noqa: E501
        :type method: str
        :param resolved_url: The resolved_url of this RetrievableOutputInner.  # noqa: E501
        :type resolved_url: str
        :param target: The target of this RetrievableOutputInner.  # noqa: E501
        :type target: str
        """
        self.swagger_types = {"format": str, "method": str, "resolved_url": str, "target": str}

        self.attribute_map = {
            "format": "format",
            "method": "method",
            "resolved_url": "resolved_url",
            "target": "target",
        }
        self._format = format
        self._method = method
        self._resolved_url = resolved_url
        self._target = target

    @classmethod
    def from_dict(cls, dikt) -> "RetrievableOutputInner":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Retrievable_output_inner of this RetrievableOutputInner.  # noqa: E501
        :rtype: RetrievableOutputInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def format(self) -> str:
        """Gets the format of this RetrievableOutputInner.


        :return: The format of this RetrievableOutputInner.
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format: str):
        """Sets the format of this RetrievableOutputInner.


        :param format: The format of this RetrievableOutputInner.
        :type format: str
        """

        self._format = format

    @property
    def method(self) -> str:
        """Gets the method of this RetrievableOutputInner.


        :return: The method of this RetrievableOutputInner.
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method: str):
        """Sets the method of this RetrievableOutputInner.


        :param method: The method of this RetrievableOutputInner.
        :type method: str
        """

        self._method = method

    @property
    def resolved_url(self) -> str:
        """Gets the resolved_url of this RetrievableOutputInner.


        :return: The resolved_url of this RetrievableOutputInner.
        :rtype: str
        """
        return self._resolved_url

    @resolved_url.setter
    def resolved_url(self, resolved_url: str):
        """Sets the resolved_url of this RetrievableOutputInner.


        :param resolved_url: The resolved_url of this RetrievableOutputInner.
        :type resolved_url: str
        """

        self._resolved_url = resolved_url

    @property
    def target(self) -> str:
        """Gets the target of this RetrievableOutputInner.


        :return: The target of this RetrievableOutputInner.
        :rtype: str
        """
        return self._target

    @target.setter
    def target(self, target: str):
        """Sets the target of this RetrievableOutputInner.


        :param target: The target of this RetrievableOutputInner.
        :type target: str
        """

        self._target = target
