# SPDX-FileCopyrightText: 2020 PANGAEA (https://www.pangaea.de/)
#
# SPDX-License-Identifier: MIT

# coding: utf-8

from datetime import date, datetime  # noqa: F401

from fuji_server import util
from fuji_server.models.base_model_ import Model
from fuji_server.models.retrievable_output_inner import RetrievableOutputInner


class RetrievableOutput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, retrievable_objects: list[RetrievableOutputInner] | None = None):
        """RetrievableOutput - a model defined in Swagger

        :param retrievable_objects: The retrievable_objects of this RetrievableOutput.  # noqa: E501
        :type retrievable_objects: List[RetrievableOutputInner]
        """
        self.swagger_types = {"retrievable_objects": list[RetrievableOutputInner]}

        self.attribute_map = {"retrievable_objects": "retrievable_objects"}
        self._retrievable_objects = retrievable_objects

    @classmethod
    def from_dict(cls, dikt) -> "RetrievableOutput":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Retrievable_output of this RetrievableOutput.  # noqa: E501
        :rtype: RetrievableOutput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def retrievable_objects(self) -> list[RetrievableOutputInner]:
        """Gets the retrievable_objects of this RetrievableOutput.


        :return: The retrievable_objects of this RetrievableOutput.
        :rtype: List[RetrievableOutputInner]
        """
        return self._retrievable_objects

    @retrievable_objects.setter
    def retrievable_objects(self, retrievable_objects: list[RetrievableOutputInner]):
        """Sets the retrievable_objects of this RetrievableOutput.


        :param retrievable_objects: The retrievable_objects of this RetrievableOutput.
        :type retrievable_objects: List[RetrievableOutputInner]
        """

        self._retrievable_objects = retrievable_objects
