# SPDX-FileCopyrightText: 2020 PANGAEA (https://www.pangaea.de/)
#
# SPDX-License-Identifier: MIT

from fuji_server import util
from fuji_server.models.base_model_ import Model
from fuji_server.models.semantic_vocabulary_output_inner import SemanticVocabularyOutputInner  # noqa: F401


class SemanticVocabularyOutput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self):
        """SemanticVocabularyOutput - a model defined in Swagger"""
        self.swagger_types = {}

        self.attribute_map = {}

    @classmethod
    def from_dict(cls, dikt) -> "SemanticVocabularyOutput":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SemanticVocabulary_output of this SemanticVocabularyOutput.  # noqa: E501
        :rtype: SemanticVocabularyOutput
        """
        return util.deserialize_model(dikt, cls)
