# SPDX-FileCopyrightText: 2020 PANGAEA (https://www.pangaea.de/)
#
# SPDX-License-Identifier: MIT

# coding: utf-8

from datetime import date, datetime  # noqa: F401

from fuji_server import util
from fuji_server.models.base_model_ import Model
from fuji_server.models.standardised_protocol_output_inner import StandardisedProtocolOutputInner


class StandardisedProtocolOutput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, standard_protocol: list[StandardisedProtocolOutputInner] | None = None):
        """StandardisedProtocolOutput - a model defined in Swagger

        :param standard_protocol: The standard_protocol of this StandardisedProtocolOutput.  # noqa: E501
        :type standard_protocol: List[StandardisedProtocolOutputInner]
        """
        self.swagger_types = {"standard_protocol": list[StandardisedProtocolOutputInner]}

        self.attribute_map = {"standard_protocol": "standard_protocol"}
        self._standard_protocol = standard_protocol

    @classmethod
    def from_dict(cls, dikt) -> "StandardisedProtocolOutput":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StandardisedProtocol_output of this StandardisedProtocolOutput.  # noqa: E501
        :rtype: StandardisedProtocolOutput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def standard_protocol(self) -> list[StandardisedProtocolOutputInner]:
        """Gets the standard_protocol of this StandardisedProtocolOutput.


        :return: The standard_protocol of this StandardisedProtocolOutput.
        :rtype: List[StandardisedProtocolOutputInner]
        """
        return self._standard_protocol

    @standard_protocol.setter
    def standard_protocol(self, standard_protocol: list[StandardisedProtocolOutputInner]):
        """Sets the standard_protocol of this StandardisedProtocolOutput.


        :param standard_protocol: The standard_protocol of this StandardisedProtocolOutput.
        :type standard_protocol: List[StandardisedProtocolOutputInner]
        """

        self._standard_protocol = standard_protocol
